<form method="post" action="./?page=CreateJokeOk">
    <p>
      <input type="radio" name="Category" value="Enfant"> Enfant
      <input type="radio" name="Category" value="Famille"> Famille
      <input type="radio" name="Category" value="Autre"> Autre
      <input type="radio" name="Category" value="Juif"> Juif
    </p>
    <p>
    <input type="text" name="Deb" placeholder="Début de la blague" >
    <input type="text" name="Fin" placeholder="Réponse">
    </p>
    <p>
        <input type="submit" value="Valider" />
    </p>
</form>