<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="./">TP Java</a>
    <a class="navbar-brand" href="./?page=CreateJoke">Créer une blague</a>
  </div>

</div><!-- /.container-fluid -->
</nav>
<style>
.navbar{
margin:0;  
}
</style>